version: '3'

services:
  # Node.js
  node:
    build: .
    container_name: node
    tty: true
    ports:
      - "3000:3000"
    # プロジェクトディレクトリにマウントする
    volumes:
      - .:/var/www
    # ネットワーク
    networks:
      - default

# ネットワーク
networks:
  default:
    driver: bridge